# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Videos by John Doe
description: My name is John Doe, and these are my videos.
url: http://localhost:4000/
author:
  name: John Doe
  url: http://example.com/
baseurl: /
video-baseurl: /videos/
up-next-count: 5

# ----------------------- #
#    Optional Features    #
# ----------------------- #

subscribe-button-url: http://example.com/ # If a url is provided, a subscribe button under the video will lead to it
allow-video-embeds: true # Allow users to get embed code for your videos (warning: your videos will be loaded from embeds on external sites!)
disqus-shortname:  # If a Disqus shortname is provided here, a Disqus thread will be created for each video.

# ----------------------- #
#     Static Configs      #
# ----------------------- #

permalink: /watch/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: watch
      title: Video Title
      categories: [uploads]
