# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Videos by John Doe
description: My name is John Doe, and these are my videos.
url: http://localhost:4000/
author:
  name: John Doe
  url: http://example.com/
baseurl: /
video-baseurl: /video/
up-next-count: 5

# ----------------------- #
#    Optional Features    #
# ----------------------- #

# If a url is provided, a subscribe button under the video will lead to it (hint: use something like a MailChimp subscribe page!)
subscribe-button-url: http://example.com/ 

# Allow users to get embed code for your videos (warning: your videos will be loaded through embeds on external sites!)
allow-video-embeds: true

# If a Disqus shortname is provided here, a Disqus comment thread will be created for each video.
disqus-shortname: 

# ----------------------- #
#     Static Configs      #
# ----------------------- #

permalink: /watch/:title/
exclude: [source_videos]

category_archive:
    slugify: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: watch
